[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aspect-stable"
version = "0.3.0"
readme = "README.rst"
requires-python = ">=3.10"
license = {file = "COPYING"}
authors = [{name = "Vital Fernández", email = "vgf@umich.edu"}]
description = "Automatic SPEctra Components Tagging"
dependencies = ["numpy~=2.2",
                "joblib~=1.4",
                "matplotlib~=3.10",
                "scikit-learn~=1.6",
                "tomli >= 2.0.0 ; python_version < '3.11'"]

classifiers = ["License :: OSI Approved :: MIT License",
               "Programming Language :: Python :: 3",
               "Programming Language :: Python :: 3.7"]

[project.optional-dependencies]
docs = ["nbsphinx~=0.9",
        "ipympl~=0.9",
        "sphinx-rtd-theme~=3.0"]

tests = ["pytest~=8.3",
         "pytest-cov~=6.0",
         "pytest-mpl~=0.17"]

[tool.pytest.ini_options]
pythonpath = ["src"]
mpl-baseline-path = 'tests/baseline'
mpl-results-path = 'tests/outputs'
mpl-results-always = false
#addopts = "--cov-report term --cov-report xml"